### ISSUE TITLE
Feedback says success but not receiving any notification

### ISSUE THREAD

**Issue by app-web-dev** [Edujugon/PushNotification#32] opened 2017-11-01 17:20 UTC
Hi There,

I have used your doc and manage to send push and I get feedback below but not receiving any notification on my iPhone.

{
    "success": 1,
    "failure": 0,
    "tokenFailList": []
}

**Comment by Edujugon** [comment] 2017-11-01 17:25
Hi @app-web-dev ,

I would recommend to have a look at your app (mobile) code since most probably the issue is there.
That feedback you're getting comes from Apple's respond. It means the notification arrived successfully to Apple server.

**Comment by Edujugon** [comment] 2017-11-04 10:12
I'm closing this since it seems not to be an issue related to the package.

If you still face the same issue, feel free to comment again.

**Closed by Edujugon** 2017-11-04 10:12 UTC

**Comment by vafrcor** [comment] 2018-03-09 03:09
@Edujugon : I had similiar issue while using FCM service (there is no message arrived on iOS).

Send notification feedback displayed as below:
```json
{
  "multicast_id": 7386959461301428156,
  "success": 1,
  "failure": 0,
  "canonical_ids": 0,
  "results": [
    {
      "message_id": "0:1520560476877563%f28b2699f28b2699"
    }
  ]
}
```

If I use FCM Console to send message, there is no problem at all.

any help about this issue?

**Comment by Edujugon** [comment] 2018-03-11 19:39
Hi @vafrcor ,

I've been reviewing the code and I don't see any problem when sending through FCM.
Could you recheck the config in your FCM panel? make sure everything is set up for sending notifications to IOS.

Could you please try to test/debug it deeper and let me know if you find any clue on this?
